# bundle install --path vendor/bundle --without production

# Gemの取得先を指定する
source "http://rubygems.org/"

# Sinatra
gem "sinatra"

# Unicorn
gem 'unicorn'

# foreman
gem 'foreman'

# テストグループにRSpecを指定する
group :test do
  gem "rspec"
end
